<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>{{GROUP_ID}}</groupId>
  <artifactId>{{ARTIFACT_ID}}</artifactId>
  <version>{{PROJECT_VERSION}}</version>
  <packaging>im_module</packaging>
  
  <name>{{PROJECT_NAME}}</name>

    <parent>
        <groupId>jp.co.intra_mart</groupId>
        <artifactId>parent</artifactId>
        <version>8.0.6-2025-spring</version>
    </parent>

    <build>
        <plugins>
            <plugin>
                <groupId>jp.co.intra_mart.harness</groupId>
                <artifactId>xml-validator-maven-plugin</artifactId>
                <version>{{XML-VALIDATOR-MAVEN-PLUGIN-VERSION}}</version>
            </plugin>
            <plugin>
                <groupId>jp.co.intra_mart.harness</groupId>
                <artifactId>java-formatter-maven-plugin</artifactId>
                <version>{{JAVA-FORMATTER-MAVEN-PLUGIN-VERSION}}</version>
            </plugin>
        </plugins>
    </build>

</project>
